### PR TITLE
Fix samples to use best SKU 

### PR DESCRIPTION
**Pull request by xanwal**
# PR into Azure/azureml-examples

## Checklist

I have:

- [X] read and followed the contributing guidelines

## Changes
- Update Standard_F2s_v2 to Standard_DS2_v2 in CLI endpoints
- Update Standard_F4s_v2 to Standard_DS2_v2 in MLFlow

fixes #

### CODE REVIEW

**Comment by xanwal** [comment]
RE Product Backlog Item 1763859 - Fix all samples to use best SKU

**Comment by shivanissambare** [comment]
@xanwal can we also update the mlflow sample sku - https://github.com/Azure/azureml-examples/tree/main/cli/endpoints/online/mlflow

**Comment by xanwal** [comment]
> @xanwal can we also update the mlflow sample sku - https://github.com/Azure/azureml-examples/tree/main/cli/endpoints/online/mlflow

Done.

**Comment by shivanissambare** [comment]
why are the tests running against amlarc for changes in managed yamls :0

**Comment by shivanissambare** [comment]
@lostmygithubaccount  cody, can you please help us here
why are the tests running against amlarc samples, if the changes were only made to managed yamls

**Comment by lostmygithubaccount** [comment]
@shivanissambare the "cli-scripts-deploy-safe-rollout-k8s-online-endpoints" workflow? seems like it triggers on any changes under `/cli/endpoints/online/**` so that's expected:

image

**Comment by shivanissambare** [comment]
@xanwal are all the tests on mir samples running as expected?
we can approve this PR, since we are not really making any changes to amlarc

**Comment by xanwal** [comment]
Yes, the deployments are successful, and we can go ahead with the change. Two caveats - SAI and UAI are not fully testable for me due to AD role creation perms, and the lightgbm model on MLFlow fails with a ResourceNotReady error, however it also fails with the existing Standard_F2s_v2 SKU and looks like it's a userspace error related to the code itself. I will dig deeper to see if I can fix after wrapping up some sample deliverables. 

> @xanwal are all the tests on managed endpoints samples running as expected? let's try to get this PR approved, since we are not really making any changes to amlarc

**Review by shivanissambare — APPROVED** [review]

**Comment by shivanissambare** [comment]
@shmahe whenever you get a chance, we are updating the SKUs based on our internal teams discussion 
updating to the SKU with better memory and cheaper in cost

**Review by shmahe — APPROVED** [review]

**Pull request merged**
