### PR TITLE
Users/anksing/logging example

### PR DESCRIPTION
**Pull request by singankit**
# PR into Azure/azureml-examples

## Checklist

I have:

- [X] read and followed the contributing guidelines

## Changes
Samples show casing usage of mlflow logging API's during training
-

fixes #

### CODE REVIEW

**Comment by lostmygithubaccount** [comment]
nearly all training examples show logging via mlflow - can you separate out the #146 fix from the sklearn example?

**Comment by lostmygithubaccount** [comment]
also `mlflow.start_run()` is not needed

**Comment by singankit** [comment]
> nearly all training examples show logging via mlflow - can you separate out the #146 fix from the sklearn example?

@shivp950 to review this ask.

**Comment by lostmygithubaccount** [comment]
why does this new example need to be tied to fixing #146? the ask is simply to separate the two

**Comment by singankit** [comment]
> why does this new example need to be tied to fixing #146? the ask is simply to separate the two

Will raise a separate PR for issue #146.

**Comment by singankit** [comment]
> also `mlflow.start_run()` is not needed

Have addressed this comment. Thanks.

**Comment by shivp950** [comment]
looks good to me, @lostmygithubaccount is the folder structure okay with you?

**Pull request merged**
