### PR TITLE
Use enable_blob_mount=False for image model deployment

### PR DESCRIPTION
**Pull request by PhaniShekhar**
# PR into Azure/azureml-examples

## Checklist

I have:

- [x] read and followed the contributing guidelines

## Changes

- Use enable_blob_mount=False for model deployment with AutoML Image v1 notebooks.

fixes #

### CODE REVIEW

**Comment by rdondera-microsoft** [comment]
#add-reviewer:rdondera-microsoft

**Review by rdondera-microsoft — APPROVED** [review]
LGTM - running black locally.

**Comment by PhaniShekhar** [comment]
#assign-reviewer:sharma-riti

**Comment by rdondera-microsoft** [comment]
#assign-reviewer:risha

**Review by sharma-riti — APPROVED** [review]

**Comment by PhaniShekhar** [comment]
The failures are due to the workflow setup and not related to the changes in the PR. The webservice deployed works when request is send from inside corpnet.

**Pull request merged**
