### PR TITLE
Add R custom container sample

### PR DESCRIPTION
**Pull request by gvashishtha**
# PR into Azure/azureml-examples

## Checklist

I have:

- [x] read and followed the contributing guidelines

## Changes

-

fixes #

### CODE REVIEW

**Comment by gvashishtha** [comment]
#363 talks about training but this PR is also relevant (I think plumber is considered modern)

**Comment by danielsc** [comment]
great example -- love it.
can you add a readme to it, though, so it is easier to understand how to use it?

**Comment by lostmygithubaccount** [comment]
should "R" be uppercase or lowercase? currently in training it is "r"

**Comment by lostmygithubaccount** [comment]
also is there or will there be a corresponding doc talking about this? @gvashishtha

**Comment by gvashishtha** [comment]
@lostmygithubaccount "R" is standard I believe: https://www.r-project.org/

**Comment by gvashishtha** [comment]
No plan to add a doc at the moment since the script steps are essentially identical to those that are captured in [this doc](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-custom-container)

**Comment by lostmygithubaccount** [comment]
yeah, let's keep the directory paths all lowercase through for consistency - e.g. we use "lightgbm" instead of "LightGBM"

**Review by lostmygithubaccount — APPROVED** [review]
looks good, you may want to add the YAML frontmatter to the README.md so the sample shows on docs.microsoft.com/samples

**Review by niyer-msft — APPROVED** [review]

**Pull request merged**
