### PR TITLE
Sklearn autolog example

### PR DESCRIPTION
**Pull request by janhavi13**
# PR into Azure/azureml-examples

## Checklist

I have:

- [ ] read and followed the contributing guidelines
- [ ] ran `python readme.py` after making changes (per contributing guidelines)
- [ ] added required testing (per contributing guidelines)

## Changes

-

fixes #

### CODE REVIEW

**Comment by lostmygithubaccount** [comment]
can you just replace the existing training script instead of making a new one? also as is this script isn't called in any workflows so it won't be run

**Comment by lostmygithubaccount** [comment]
ah - also can you develop on a branch? you should have access

**Review by lostmygithubaccount — CHANGES_REQUESTED** [review]
- develop on branch
- fill out PR template
- replace existing script instead of creating a new one

**Comment by janhavi13** [comment]
> ah - also can you develop on a branch? you should have access

Ah, I tried that but I couldn't push to a remote branch :(  I'll look into it again.

**Comment by lostmygithubaccount** [comment]
i added you - on a side note I need to find a way to give everyone in Azure write permissions...

**Pull request closed without merging**
