### PR TITLE
Dan's Triton and Triton Custom Container Samples

### PR DESCRIPTION
**Pull request by xanwal**
# PR into Azure/azureml-examples

## Checklist

I have:

- [x] read and followed the contributing guidelines

## Changes

- Added online-endpoints-triton.ipynb
- Added online-endpoints-triton-cc.ipynb

fixes #

### CODE REVIEW

**Comment by xanwal** [comment]
Please note the smoke/build black reformatting is taken care of by my other outstanding examples PR  https://github.com/Azure/azureml-examples/pull/1595

**Comment by xanwal** [comment]
> Could you place the files under `endpoints/online/triton/single-model/` to follow the structure of CLI? Using the same directory structure makes customer easier to compare, and avoid changing structure when we add other examples like `multi-model` and so on.

Moving the Triton one now - do you want the custom container one there too? For the CLI custom container ones we put them in their own container and plan to consolidate them into folders.

**Comment by shohei1029** [comment]
Could you add description for pip requirements?
```
pip install numpy
pip install tritonclient[http]
pip install pillow
pip install gevent
```

**Comment by shohei1029** [comment]
> Moving the Triton one now - do you want the custom container one there too? For the CLI custom container ones we put them in the custom-container folder flat right now and plan to consolidate them into folders.

I think the customer container one is fine in the custom-container directory; the NCD is special, and I want to keep the directories separate.
Maybe we can put an explanation somewhere in the documentation so that customers don't get confused...

I agree in the sense of further dividing the custom container directory, since quite a lot of files are now placed in the flat. However, we may have to modify the corresponding documentation as well.

**Comment by shohei1029** [comment]
For the peacock image,
Thanks for uploading the original image we had, but we're not sure about the license for that image to be public.
I re-link the peacock image to the one in the public domain (free to use). I think we can replace the image with the link (and modify codes to use the link) if this works well for the sample notebook.
http://aka.ms/peacock-pic

**Comment by xanwal** [comment]
> For the peacock image, Thanks for uploading the original image we had, but we're not sure about the license for that image to be public. I re-link the peacock image to the one in the public domain (free to use). I think we can replace the image with the link (and modify codes to use the link) if this works well for the sample notebook. http://aka.ms/peacock-pic

In order to download the image I had to set a User-Agent per this page: https://meta.wikimedia.org/wiki/User-Agent_policy. I set it to f"Python Requests/{requests.__version__} (https://github.com/Azure/azureml-examples)". Let me know if there's a better way to approach that.

**Comment by shohei1029** [comment]
> In order to download the image I had to set a User-Agent per this page: https://meta.wikimedia.org/wiki/User-Agent_policy. I set it to f"Python Requests/{requests.**version**} (https://github.com/Azure/azureml-examples)". Let me know if there's a better way to approach that.

Oh, I see. Let me stop directly linking to the image in Wikipedia. Could you replace the current image `peacock-image.png` with the image in the Wikipedia? (Because it's public domain.)
I'll re-link https://aka.ms/peacock-pic to the image.

**Comment by xanwal** [comment]
> > In order to download the image I had to set a User-Agent per this page: https://meta.wikimedia.org/wiki/User-Agent_policy. I set it to f"Python Requests/{requests.**version**} (https://github.com/Azure/azureml-examples)". Let me know if there's a better way to approach that.
> 
> Oh, I see. Let me stop directly linking to the image in Wikipedia. Could you replace the current image `peacock-image.png` with the image in the Wikipedia? (Because it's public domain.) I'll re-link https://aka.ms/peacock-pic to the image.

It's already changed in the code and passing the build although I do need to delete the image from the repo in the next commit. I'm not sure linking directly will solve it but let's try it - the response I got without it was a Wikimedia text response accompanying a 403.

**Comment by shohei1029** [comment]
Thank you. Either way is fine :)

**Review by shohei1029 — APPROVED** [review]
I've confirmed working for both online-endpoints-triton.ipynb and ~online-endpoints-triton-cc.ipynb~.
Thanks a lot for the outstanding PR.

**Comment by shohei1029** [comment]
@dem108 Could you review and confirm?

**Review by dem108 — APPROVED** [review]

**Pull request merged**
