### PR TITLE
Add MLflow-V1 Tracking Comparison Notebook

### PR DESCRIPTION
**Pull request by needuv**
# PR into Azure/azureml-examples

## Checklist

I have:

- [x] read and followed the contributing guidelines

## Changes

Add a notebook that compares v1 SDK tracking to mlflow tracking.

fixes #

### CODE REVIEW

**Review by lostmygithubaccount — CHANGES_REQUESTED** [review]
The notebook itself looks great! A few things needed:

- separate out from `notebooks/basics`? can go in a new directory `notebooks/mlflow-comparison` or just `notebooks/mlflow`
- format the notebook with `black` and/or `black-nb`
- run `python readme.py` to generate the GitHub Action file to test this notebook
    - may need some minor adjustments, e.g. installing requirements in the notebook

Note that all the tests are failing right now due to an unrelated issue Harneet is working to fix.

Also I'd prefer we not have images (pngs, jpegs) to reduce repo size and ensure it's doing one thing well (code examples). Along those lines some of this reads as documentation more than code example, but I think that's okay for this notebook. Would defer to @balapv for guidance.

**Comment by balapv** [comment]
Agree with Cody. There is a good amount of documentation inside the notebook. We would prefer the samples to be light and stick to only code as much as possible. Documentation tends to get stale and documentation inside sample notebooks don't get updated. For now it is fine, but I would suggest to create a page or a section somewhere in docs for this scenario if we want to provide documentation.

**Comment by needuv** [comment]
@lostmygithubaccount @balapv, that makes sense re: documentation. I don't think our documentation on this topic is very robust yet, so I'd rather leave it in the notebook for now and re-evaluate once the doc story is better. @AbeOmor @singankit FYI-- we should figure out docs for mlflow/v1 comparisons.

**Comment by singankit** [comment]
> @lostmygithubaccount @balapv, that makes sense re: documentation. I don't think our documentation on this topic is very robust yet, so I'd rather leave it in the notebook for now and re-evaluate once the doc story is better. @AbeOmor @singankit FYI-- we should figure out docs for mlflow/v1 comparisons.

Agreed the original idea was to use this notebook to pull code snippets for full fledged public facing doc. However every detail in this notebook cannot be pulled in a public facing doc (too much info for doc in my opinion) hence the need to add comments in the notebook. Cody made some great points about moving it to a separate folder since we might have more notebooks on this topic.

**Review by lostmygithubaccount — APPROVED** [review]

**Review by singankit — APPROVED** [review]

**Pull request merged**
