### PR TITLE
Ayushmishra/model import without mlflow conversion

### PR DESCRIPTION
**Pull request by novaturient95**
# Description

# Checklist

- [x] I have read the [contribution guidelines](https://github.com/Azure/azureml-examples/blob/main/CONTRIBUTING.md)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by skasturi** [comment]
Smoke tests seem to fail?

**Comment by skasturi** [comment]
Let us rename/repurpose this to "bring your model into AzureML" from different data sources. And give generic blob/git as the source without MLFlow conversion. 

Cc: @ManojBableshwar @swatig007 @manashgoswami @rtanase

**Comment by novaturient95** [comment]
abandoning this because of unrelated changes that got added.

**Comment by novaturient95** [comment]
Created a new PR: https://github.com/Azure/azureml-examples/pull/2296. Please help to review.
Thanks

**Pull request closed without merging**
