### PR TITLE
Delete input_example.json

### PR DESCRIPTION
**Pull request by tracychms**
# PR into Azure/azureml-examples

## Checklist

I have:

- [ ] read and followed the contributing guidelines

## Changes

-

fixes #

### CODE REVIEW

**Comment by tracychms** [comment]
fix bug: https://msdata.visualstudio.com/Vienna/_workitems/edit/1305568

**Review by bstollnitz — APPROVED** [review]
Looks good. However, I was wondering... how did the file get there in the first place? It's in the same directory as other generated MLflow model files, so I wonder if it got put there when saving the model. In which case, it may come back if the model gets saved again...

**Comment by tracychms** [comment]
> Looks good. However, I was wondering... how did the file get there in the first place? It's in the same directory as other generated MLflow model files, so I wonder if it got put there when saving the model. In which case, it may come back if the model gets saved again...

the model is not auto saved. it's checked-in manually from an offline training job. the file won't be added again later. and we are not using this file when auto generate the scoring script, safe to remove to avoid confusion.

**Comment by bstollnitz** [comment]
Thanks for the info. It sounds good!

**Pull request merged**
