### PR TITLE
Added mirror traffic section in online-endpoints-safe-rollout.ipynb

### PR DESCRIPTION
**Pull request by shohei1029**
# PR into Azure/azureml-examples

## Checklist

I have:

- [x] read and followed the contributing guidelines

## Changes

- Added mirror traffic section in SDKv2 example for managed online endpoints to align with the CLIv2 example.

fixes #

### CODE REVIEW

**Comment by shohei1029** [comment]
@dem108 
We've discussed that in order to pass the tests, we would try using `create_or_update()` method instead of `begin_create_or_update()` method. However, I found that the `create_or_update()` method was not for endpoint or deployment. I've tested the code works properly, so could you approve if there are no other problems?

[azure.ai.ml.MLClient class | Microsoft Docs](https://docs.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.mlclient?view=azure-python-preview#azure-ai-ml-mlclient-create-or-update)

**Comment by dem108** [comment]
> @dem108 We've discussed that in order to pass the tests, we would try using `create_or_update()` method instead of `begin_create_or_update()` method. However, I found that the `create_or_update()` method was not for endpoint or deployment. I've tested the code works properly, so could you approve if there are no other problems?
> 
> [azure.ai.ml.MLClient class | Microsoft Docs](https://docs.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.mlclient?view=azure-python-preview#azure-ai-ml-mlclient-create-or-update)

Okay, I see that create_or_update() does not take the endpoint/deployment. But why does the workflow fails while yours succeeds? When it succeeded, did you use new endpoint and deployment names?

**Comment by shohei1029** [comment]
Endpoint name must be different for each run because the name will be generated by current time as 
`online_endpoint_name = "endpoint-" + datetime.datetime.now().strftime("%m%d%H%M%f")`.

I thought that the reason for workflow failure was that the sample JSON for scoring was out of the working directory for the workflow, because working directory for running the notebook was `sdk/endpoints/online/managed` but the ` sample-request.json` was out of that directory.
I'm not sure because the error in the workflow said `JSONDecodeError` but when I tried to remove .json in my local, the error was `FileNotFoundError`, it was different.. :(

c.f.
workflow: https://github.com/Azure/azureml-examples/actions/runs/2872466845/workflow

**Review by xanwal — APPROVED** [review]
image

Maybe run readme.py before merging but other than that looks great. We have started putting  Standard DS2v2 instead of the F series for compute, but that may be another PR.

**Review by xanwal — APPROVED** [review]

**Comment by shohei1029** [comment]
Oh I didn't know that the redme.py would change kernelspec for us. I l also replaced that with Standard_DS2_v2. Thank you✨

**Pull request merged**
