### PR TITLE
updated minimal image version for the cli examples

### PR DESCRIPTION
**Pull request by sshiri-msft**
# Description

# Checklist

- [x] I have read the contribution guidelines.
  - [General](https://github.com/Azure/azureml-examples/blob/main/CONTRIBUTING.md)
  - [SDK](https://github.com/Azure/azureml-examples/blob/main/sdk/CONTRIBUTING.md)
  - [CLI](https://github.com/Azure/azureml-examples/blob/main/cli/CONTRIBUTING.md)
- [x] I have coordinated with the docs team (mldocs@microsoft.com) if this PR deletes files or changes any file names or file extensions.
- [ ] Pull request includes test coverage for the included changes.
- [ ] This notebook or file is added to the [CODEOWNERS](https://github.com/Azure/azureml-examples/blob/main/.github/CODEOWNERS) file, pointing to the author or the author's team.

### CODE REVIEW

**Review by siyigao1212 — APPROVED** [review]

**Review by arunsu — APPROVED** [review]

**Review by sorazy — APPROVED** [review]
lgtm

**Comment by dem108** [comment]
Why are workflows not creating deployments? We should test create deployments to ensure the version changes don't break the examples.

**Comment by sshiri-msft** [comment]
> Why are workflows not creating deployments? We should test create deployments to ensure the version changes don't break the examples.
workflows create deployment: https://github.com/Azure/azureml-examples/actions/runs/10236412389/job/28318425364

**Comment by sshiri-msft** [comment]
There are two types of files in the workflows, one cli-script-* which does deployment and cli-endpoints-* does not do deployment only creates endpoint
[azureml-examples/.github/workflows at sshiri/fix_touchserve_issue · Azure/azureml-examples](https://github.com/Azure/azureml-examples/tree/sshiri/fix_touchserve_issue/.github/workflows)
Maybe we can address this in different PR

**Comment by aishanibhalla** [comment]
lgtm

**Review by aishanibhalla — APPROVED** [review]

**Pull request merged**
