### PR TITLE
Fixing duplicate tags

### PR DESCRIPTION
**Pull request by Blackmist**
When there's duplicate XML style tags used for import into docs, the last one is the one that matches. Changing tag to be unique.

# PR into Azure/azureml-examples

## Checklist

I have:

- [ x ] read and followed the contributing guidelines

## Changes
Changed comments to have a unique xml-style name
-

fixes #

### CODE REVIEW

**Comment by Blackmist** [comment]
@shohei1029 @dem108 can someone merge? Unblocking snippet import into docs.

**Comment by dem108** [comment]
Thanks for catching this! Do we need a PR for docs update too?

**Review by dem108 — APPROVED** [review]
This looks good. Thanks!

**Comment by Blackmist** [comment]
> Thanks for catching this! Do we need a PR for docs update too?

Working on the doc also. Getting ready to add another fix to this PR however - looks like the name the model is registered as (sklearn) isn't what the deployment uses (score-sklearn).

**Review by shohei1029 — APPROVED** [review]

**Comment by shohei1029** [comment]
Thanks for the PR! I'll merge it.

**Pull request merged**
