### PR TITLE
Remove inference-schema dependencies

### PR DESCRIPTION
**Pull request by xanwal**
# PR into Azure/azureml-examples

## Checklist

I have:

- [x] read and followed the contributing guidelines

## Changes

- Remove inference-schema package dependencies in Conda envs

fixes #

### CODE REVIEW

**Comment by shivanissambare** [comment]
@xanwal can you run these scripts as part of your PR change, so samples are using these conda yamls are working as expected

https://github.com/Azure/azureml-examples/blob/main/cli/deploy-managed-online-endpoint.sh
https://github.com/Azure/azureml-examples/blob/main/cli/deploy-safe-rollout-online-endpoints.sh

**Comment by xanwal** [comment]
> @xanwal can you run these scripts as part of your PR change, so samples are using these conda yamls are working as expected
> 
> https://github.com/Azure/azureml-examples/blob/main/cli/deploy-managed-online-endpoint.sh https://github.com/Azure/azureml-examples/blob/main/cli/deploy-safe-rollout-online-endpoints.sh

On it, thanks.

**Comment by xanwal** [comment]
> @xanwal can you run these scripts as part of your PR change, so samples are using these conda yamls are working as expected
> 
> https://github.com/Azure/azureml-examples/blob/main/cli/deploy-managed-online-endpoint.sh https://github.com/Azure/azureml-examples/blob/main/cli/deploy-safe-rollout-online-endpoints.sh

@shivanissambare 
Confirmed for both. I will ping you with some logs. Thanks.

**Review by shivanissambare — APPROVED** [review]

**Comment by shivanissambare** [comment]
@shmahe  we need two approvers to merge the PR, can you please take a look!
removing dependency on `inference-schema` version and using `azureml-defaults` 1.38

**Review by shmahe — APPROVED** [review]

**Comment by shivanissambare** [comment]
@xanwal changes are approved, you can merge this PR

**Pull request merged**
