### PR TITLE
Model import Notebook and workflow

### PR DESCRIPTION
**Pull request by HrishikeshGeedMS**
# Description
Changed workflow to test foundation model notebooks

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/Azure/azureml-examples/blob/main/CONTRIBUTING.md)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by skasturi** [comment]
>     "# submit the pipeline job\n",

Could we add step to check status of the job & print the model once it is imported? 

---
Refers to: sdk/python/foundation-models/system/import/import_model_into_registry.ipynb:335 in a203d8e. [](commit_id = a203d8e1a65394b9a122d6e610c6489d9b7e53a4, deletion_comment = False)

**Comment by skasturi** [comment]
>     "    # registry_name = \"azureml-preview-test1\", pass only if you want to register model in registry\n",

Please remove

---
Refers to: sdk/python/foundation-models/system/import/import_model_into_registry.ipynb:295 in a203d8e. [](commit_id = a203d8e1a65394b9a122d6e610c6489d9b7e53a4, deletion_comment = False)

**Comment by skasturi** [comment]
>     "## Check if model already exists "

Check if the model already exists in System registry

---
Refers to: sdk/python/foundation-models/system/import/import_model_into_registry.ipynb:249 in a203d8e. [](commit_id = a203d8e1a65394b9a122d6e610c6489d9b7e53a4, deletion_comment = False)

**Comment by skasturi** [comment]
>     "model-id-screen-shot.png": {

@ManojBableshwar Could you please update this? 

---
Refers to: sdk/python/foundation-models/system/import/import_model_into_registry.ipynb:201 in a203d8e. [](commit_id = a203d8e1a65394b9a122d6e610c6489d9b7e53a4, deletion_comment = False)

**Comment by skasturi** [comment]
>     "- registry_name - This needs to be passed only when you want to register the model in the registry else ignore\n",

registry_name (optional)

---
Refers to: sdk/python/foundation-models/system/import/import_model_into_registry.ipynb:212 in a203d8e. [](commit_id = a203d8e1a65394b9a122d6e610c6489d9b7e53a4, deletion_comment = False)

**Comment by skasturi** [comment]
>     "- registry_name - This needs to be passed only when you want to register the model in the registry else ignore\n",

By default, model is imported into your workspace. If `registry_name` is passed, the pipeline will attempt to register into respective registry

---
Refers to: sdk/python/foundation-models/system/import/import_model_into_registry.ipynb:212 in a203d8e. [](commit_id = a203d8e1a65394b9a122d6e610c6489d9b7e53a4, deletion_comment = False)

**Comment by skasturi** [comment]
>     "### Set the parameter values"

Set parameter values

---
Refers to: sdk/python/foundation-models/system/import/import_model_into_registry.ipynb:227 in a203d8e. [](commit_id = a203d8e1a65394b9a122d6e610c6489d9b7e53a4, deletion_comment = False)

**Comment by skasturi** [comment]
>     "ml_client_registry = MLClient(credential, registry_name=\"azureml-preview-test1\")\n",

Update to azureml-preview for now. 

---
Refers to: sdk/python/foundation-models/system/import/import_model_into_registry.ipynb:147 in a203d8e. [](commit_id = a203d8e1a65394b9a122d6e610c6489d9b7e53a4, deletion_comment = False)

**Comment by skasturi** [comment]
>     "from azure.ai.ml import MLClient"

(nit) Merge into a single line

---
Refers to: sdk/python/foundation-models/system/import/import_model_into_registry.ipynb:81 in a203d8e. [](commit_id = a203d8e1a65394b9a122d6e610c6489d9b7e53a4, deletion_comment = False)

**Comment by skasturi** [comment]
>     "* text-to-image\n",

@ShipraJain01 Could you please cross check that this list is the final list? 

---
Refers to: sdk/python/foundation-models/system/import/import_model_into_registry.ipynb:24 in a203d8e. [](commit_id = a203d8e1a65394b9a122d6e610c6489d9b7e53a4, deletion_comment = False)

**Review by skasturi — CHANGES_REQUESTED** [review]
:clock1:

**Comment by skasturi** [comment]
>   },

@ManojBableshwar 

Are we trying OBO? 

---
Refers to: sdk/python/foundation-models/system/import/import_model_into_registry.ipynb:112 in a203d8e. [](commit_id = a203d8e1a65394b9a122d6e610c6489d9b7e53a4, deletion_comment = False)

**Comment by skasturi** [comment]
>     "## 2.1 Use registry handle to load the components in workspace\n",

Could we merge 2, 2.1 into a single 2? 

---
Refers to: sdk/python/foundation-models/system/import/import_model_into_registry.ipynb:167 in a203d8e. [](commit_id = a203d8e1a65394b9a122d6e610c6489d9b7e53a4, deletion_comment = False)

**Comment by skasturi** [comment]
>     "# 3. Create a pipeline job using the pipeline component"

May be make font sizes consistent b/w being a sub-heading, heading, sub-sub-heading etc? 



---
Refers to: sdk/python/foundation-models/system/import/import_model_into_registry.ipynb:188 in a203d8e. [](commit_id = a203d8e1a65394b9a122d6e610c6489d9b7e53a4, deletion_comment = False)

**Comment by HrishikeshGeedMS** [comment]
> > ```
> > "## Check if model already exists "
> > ```
> 
> Check if the model already exists in AzureML registry
> 
> Refers to: sdk/python/foundation-models/system/import/import_model_into_registry.ipynb:249 in [a203d8e](https://github.com/Azure/azureml-examples/commit/a203d8e1a65394b9a122d6e610c6489d9b7e53a4). [](commit_id = [a203d8e](https://github.com/Azure/azureml-examples/commit/a203d8e1a65394b9a122d6e610c6489d9b7e53a4), deletion_comment = False)

Done

**Comment by HrishikeshGeedMS** [comment]
> > > ```
> > > "## Check if model already exists "
> > > ```
> > 
> > 
> > Check if the model already exists in AzureML registry
> > Refers to: sdk/python/foundation-models/system/import/import_model_into_registry.ipynb:249 in [a203d8e](https://github.com/Azure/azureml-examples/commit/a203d8e1a65394b9a122d6e610c6489d9b7e53a4). [](commit_id = [a203d8e](https://github.com/Azure/azureml-examples/commit/a203d8e1a65394b9a122d6e610c6489d9b7e53a4), deletion_comment = False)
> 
> Done

**Comment by HrishikeshGeedMS** [comment]
> > ```
> > "# submit the pipeline job\n",
> > ```
> 
> Could we add a step to check status of the job & print the model once it is imported?
> 
> Refers to: sdk/python/foundation-models/system/import/import_model_into_registry.ipynb:335 in [a203d8e](https://github.com/Azure/azureml-examples/commit/a203d8e1a65394b9a122d6e610c6489d9b7e53a4). [](commit_id = [a203d8e](https://github.com/Azure/azureml-examples/commit/a203d8e1a65394b9a122d6e610c6489d9b7e53a4), deletion_comment = False)

Done

**Review by ManojBableshwar — APPROVED** [review]

**Review by novaturient95 — APPROVED** [review]

**Review by skasturi — APPROVED** [review]

**Pull request merged**
