### PR TITLE
add sample model in cli dir as well as sdk

### PR DESCRIPTION
**Pull request by shohei1029**
# PR into Azure/azureml-examples
The sample code and YAML in the doc [Deploy a custom container as an online endpoint](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-custom-container) will not work since there is no proper model directory.
I copied from SDK directory and confirmed the successful deployment.

## Checklist

I have:

- [x] read and followed the contributing guidelines

## Changes

- add sample model directory in cli dir as well as sdk dir to run the sample yaml file. 

fixes #

The sample model for custom container only exists in SDK directory, so I copied to CLI directory.
fom "sdk/endpoints/online/custom-container/half_plus_two" to "cli/endpoints/online/custom-container/"

### CODE REVIEW

**Comment by shohei1029** [comment]
The sample model for custom container only exists in SDK directory, so I copied to CLI directory.
fom "sdk/endpoints/online/custom-container/half_plus_two" to "cli/endpoints/online/custom-container/"
#assign-reviewer: @dem108

**Comment by shohei1029** [comment]
#assign-reviewer: @dem108

**Review by dem108 — APPROVED** [review]
I approve this change with one condition: can you confirm you could test/create deployment with this change?

Apart from this specific PR:
1. We should consider having one place (like ../models) to keep all models used in our samples, OR at least have consistency in the locations (having them under each scenario folders like mflow, tfserving etc)
2. We should add .sh script that shows how to use 3 files (dockfile, endpoint YAML, deployment YAML) in the right place.

**Comment by dem108** [comment]
#assign-reviewer: @hugoaponte

**Comment by shohei1029** [comment]
> I approve this change with one condition: can you confirm you could test/create deployment with this change?
> 
> Apart from this specific PR:
> 
> 1. We should consider having one place (like ../models) to keep all models used in our samples, OR at least have consistency in the locations (having them under each scenario folders like mflow, tfserving etc)
> 2. We should add .sh script that shows how to use 3 files (dockfile, endpoint YAML, deployment YAML) in the right place.

@dem108 Thanks for comments. 
Yes, this PR is like a first aid because the sample .sh and the sample code in the document will not work without this model directory. I confirmed the sample codes worked properly with the model directory.

**Comment by shohei1029** [comment]
Sorry I miss-included a commit. Please wait until I somehow revert it..
[bea862e](https://github.com/Azure/azureml-examples/pull/1593/commits/bea862eb5796d87688d4772baf3c4e0c62e97b61)

**Comment by dem108** [comment]
Is it ready for review? As long as test succeeded, I am okay merging it. Previous suggestion is something we can take later as a separate PR.

**Comment by shohei1029** [comment]
> Is it ready for review? As long as test succeeded, I am okay merging it. Previous suggestion is something we can take later as a separate PR.

I've reverted the commit, so this is ready for review (and hopefully merging). Thank you!

**Comment by shohei1029** [comment]
@hugoaponte Could you please give us a quick review and approval?

**Review by xanwal — APPROVED** [review]

**Pull request merged**
