### PR TITLE
Adding azureml-automl example notebooks

### PR DESCRIPTION
**Pull request by rtanase**
# PR into Azure/azureml-examples

## Checklist

I have:

- [x] read and followed the contributing guidelines

## Changes

- Added existing suite of Azure Automated ML notebooks
- Added workflow generator script for associating GitHub actions on each notebook to validate notebook content
- Automatic notebook validation has been configured to run on PRs and each Tuesday, scattered throughout the day
- Uploaded results of executing notebooks within workflow artifact, for debugging purposes
- Excluded this suite of notebooks from being tagged to be Python 3.8 compatible

fixes #

### CODE REVIEW

**Review by jeff-shepherd — COMMENTED** [review]
test_auto-ml-regression-explanation-featurization.py is the only test file that I see in the PR. Are you planning to move the others as well?

**Review by jeff-shepherd — COMMENTED** [review]
Recently added:
  - statsmodels<=0.10.2,>=0.9.0
  - arch==4.14

are missing from the automl_env.yml files.

**Review by jeff-shepherd — COMMENTED** [review]
I see a change in formatting.  Spaces after commas are removed.  I thought the standard was to have a space after a comma.

**Review by jeff-shepherd — APPROVED** [review]

**Comment by rtanase** [comment]
> I see a change in formatting. Spaces after commas are removed. I thought the standard was to have a space after a comma.

**Comment by rtanase** [comment]
> Recently added:
> 
> * statsmodels<=0.10.2,>=0.9.0
> * arch==4.14
> 
> are missing from the automl_env.yml files.

SDK version 1.32 doesn't need those pins.

**Comment by rtanase** [comment]
> I see a change in formatting. Spaces after commas are removed. I thought the standard was to have a space after a comma.

The source files are ran through black to have a consistent formatting.

**Pull request merged**
