### PR TITLE
Removing step to archive anonymous model on triton deployment

### PR DESCRIPTION
**Pull request by hugoaponte**
# Description
There is no need to archive anonymous/unregistered models since these are registered by the system and they shouldn't show up on listing models.

Furthermore, with stages, this stage transition will be disallowed and will trigger an error.

# Checklist

- [X] I have read the [contribution guidelines](https://github.com/Azure/azureml-examples/blob/main/CONTRIBUTING.md)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by corymcc — APPROVED** [review]

**Comment by santiagxf** [comment]
@hugoaponte will this imply that now unregister model deployment is now possible? I think the reason why they archive the models is because of that.

**Comment by hugoaponte** [comment]
If unregistering means deleting, V2 doesn't fully support this yet. Archiving is a slightly different operation. We offer archiving as a pseudo-alternative to delete for now.

If the user wants to archive, then the user should register the model.

**Review by nancy-mejia — APPROVED** [review]

**Comment by hugoaponte** [comment]
Any concern on merging this PR, @santiagxf?

**Comment by santiagxf** [comment]
> Any concern on merging this PR, @santiagxf?

I think the reason of archiving the models in the example is because they were registered during deployment. By unregistered models I mean deploying models that are not registered in the registry. My understanding is that this was not supported and hence deployment registers them first. As a consequence, this example is archiving them once there are not needed any more. Which I think it is still needed. Am I reading the example right?

**Comment by hugoaponte** [comment]
Thanks, @santiagxf, sorry for the delay getting back to you on this. This topic is sometimes hard!

The short answer is that since the user didn't set a name nor explicitly registered the model, users shouldn't be able to change the stage of the model (i.e., Archive).

Let me share a few things:

The definition we came up with for anonymous/unregistered assets, described [here](https://microsoft-my.sharepoint.com/:w:/p/huaponte/ES06M_3RTl1Gt6QZxHAXlFoB_msiWZWjZO8CoLjr_BwXlA?e=0VLIJM&xsdata=MDV8MDF8fDM1NzIwYjg4MjJjNDQ2ODVjYmI5MDhkYWU4NTk0ZTk5fDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDB8MHw2MzgwNzc3Njc0OTQ3ODE4ODF8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxNVFkzTWpFM09UazBPVEF5TURzeE5qY3lNVGM1T1RRNU1ESXdPekU1T2pReE16QXlaR0k0T1RVM1lqUTRZelU1T1dVNU1HTXpNRFF3TkdWaU1EZzNRSFJvY21WaFpDNTJNZz09fGQ4NGFlYjkxOTI4MDQwYmNjYmI5MDhkYWU4NTk0ZTk5fGU5OTdhMTNiMmMzMTRhZTg5ZGE4ZjE2ZjMzNWE0ZjYz&sdata=cGZhanVnRUIyZTIwRWVJMGhNcEtlektNUXdVRUhodW5YUW9yNVlFOVYxST0%3D&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2Chuaponte%40microsoft.com&OR=Teams-HL&CT=1673314937628&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzAxMDUwOTQwMCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D) is:

Anonymous/unregistered assets are system created resources. Users don't necessarily know these resources are created, and they are not listed by default on the portal or CLI. For example, an output of a job or an inline model with no name. Today the most important difference from user-created assets to system-created assets is that we don't list them by defaul.

Even though these two concepts were created at different components of the stack (anonymous CLI-MFE, unregistered MRS), the consensus back them was to assume these two concepts as the same, and we would put some order when asset stages are developed.

In the context of stages, being these system-created assets, they are created as "Tracked" (i.e. MLFlow logged), and the understanding is that users shouldn't care about moving them to different stages: Archived, Production, etc. and if they care, they need to register the asset, so it is now in the Registered stage.

As additional context, delete is not a stage per se, and I assume delete will be allowed on any asset independently of the stage. So, eventually, users will be able to delete even anonymous/unregistered assets.

**Pull request merged**
